blueprint:
  name: 🚪 Contact Sensor Left Open Notification by Malte
  description: |
    📲 Notifies you when a door or window is left open.

    Are you tired of worrying about open doors or windows? This blueprint has got you covered! It's designed to send you a prompt notification when a door or window remains open for a specified duration.
 
    📖 For Details see this [Blog post](https://community.home-assistant.io/t/contact-sensor-door-or-window-left-open-notification/652571)

  domain: automation
  source_url: https://gist.github.com/Raukze/27fe0c6bf6d91b8ae2ab5e11880509ba
  input:
    trigger_entity:
      name: 🤖 Entity
      description: |
        The entity that will trigger the automation. This must be a binary sensor or input_boolean. (e.g., binary_sensor.fridge)
      selector:
        entity:
          domain:
            - binary_sensor
            - input_boolean
    friendly_name:
      name: 🏷️ Device Friendly Name
      description: What should we call the entity in the notification? (e.g., Fridge)
      default: ""
      selector:
        text:
    issue_state:
      name: ⚠️ Issue State
      description: |
        The state that triggers the automation. Because this is a binary sensor, it can only be on or off. Use the developer tools to find the correct setting.
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    duration_issue_state:
      name: ⏰ Time before alert
      description: The amount of time that the device can be in the issue state before an alert is triggered.
      default:
        minutes: 10
      selector:
        duration:
          enable_day: true
    delete_notification:
      name: 🗑️ Delete notification when not in issue state anymore.
      description: |
        Do you want the notification to be deleted automatically when the device state is not in the issue state anymore.
      default: "true"
      selector:
        boolean:
    duration_from_issue_state:
      name: ⏰ Time from issue state before alert removal
      description: |
        The amount of time that the device has not been in the issue state before the alert gets removed.
      default:
        seconds: 5
      selector:
        duration:
          enable_day: true
    notify_services_string:
      name: 📲 Notify Services
      description: |
        The service that will be called to deliver the notification. (e.g., notify.mobile_app_my_phone).
        It also supports multiple services, separated by a comma. (e.g., notify.mobile_app_my_phone,notify.mobile_app_my_spouse_phone).
      default: "notify.mobile_app_<your_device_id_here>"
      selector:
        text:
    notification_click_url:
      name: 🔗 Click URL
      description: |
        Where the user will be taken if they tap the notification. (e.g., /lovelace/kitchen)
      default: "/lovelace/ROOM"
      selector:
        text:
    notification_title:
      name: 📌 Notification Title
      description: The title of the notification.
      default: "The {{ friendly_name }} was left open"
      selector:
        text:
    notification_message:
      name: 📬 Notification Message
      description: |
        The message of the notification.
      default: "The {{ friendly_name }} was left open at {{ as_timestamp(now()) | timestamp_custom('%T', True) }}."
      selector:
        text:
    notification_icon_warning:
      name: 🚨 Notification Icon (Android Only)
      description: |
        The icon that is shown when the issue is reported. (e.g., mdi:fridge-alert)
      default: "alert"
      selector:
        select:
          options:
            - alert
            - alert-circle
            - door
            - door-open
            - motion-sensor
            - fridge
            - fridge-alert
            - home
            - home-alert
            - home-assistant
    notification_color:
      name: 🌈 Notification Color (Android Only)
      description: The color of the notification.
      default: "red"
      selector:
        select:
          options:
            - "red"
            - "orange"
            - "yellow"
            - "green"
            - "blue"
            - "purple"
    notification_interruption_level:
      name: 🔔 Interruption Level (iOS Only)
      description: |
        The intrusiveness of the notification received. This also determines whether the notification will be delivered while the device is in a focus mode.
      default: "active"
      selector:
        select:
          options:
            - passive
            - active
            - time-sensitive
            - critical

mode: restart
max_exceeded: silent
variables:
  friendly_name: !input friendly_name
  trigger_entity: !input trigger_entity
  issue_state: !input issue_state
  duration_issue_state: !input duration_issue_state
  delete_notification: !input delete_notification
  duration_from_issue_state: !input duration_from_issue_state
  notify_services_string: !input notify_services_string
  notification_click_url: !input notification_click_url
  notification_title: !input notification_title
  notification_message: !input notification_message
  notification_icon_warning: !input notification_icon_warning
  notification_color: !input notification_color
  notification_interruption_level: !input notification_interruption_level

trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: !input issue_state
    for: !input duration_issue_state
    id: send_notification
  - platform: state
    entity_id: !input trigger_entity
    from: !input issue_state
    for: !input duration_from_issue_state
    id: delete_notification
action:
  - variables:
      notify_services_list: "{{ notify_services_string.split(',') }}"
      number_of_notify_services: "{{ notify_services_list | count }}"

  - choose:
      - conditions:
          - condition: trigger
            id: send_notification
        sequence:
          - repeat:
              count: "{{ number_of_notify_services }}"
              sequence:
                - service: "{{ notify_services_list[repeat.index-1] }}"
                  data:
                    message: !input notification_message
                    title: !input notification_title
                    data:
                      clickAction: !input notification_click_url
                      url: !input notification_click_url
                      tag: "{{ trigger_entity }}-{{ friendly_name }}-{{ notify_services_string }}"
                      color: !input notification_color
                      notification_icon: "mdi:{{ notification_icon_warning }}"
                      push:
                        interruption-level: !input notification_interruption_level
      - conditions:
          - condition: trigger
            id: delete_notification
          - "{{ delete_notification }}"
        sequence:
          - repeat:
              count: "{{ number_of_notify_services }}"
              sequence:
                - service: "{{ notify_services_list[repeat.index-1] }}"
                  data:
                    message: "clear_notification"
                    data:
                      tag: "{{ trigger_entity }}-{{ friendly_name }}-{{ notify_services_string }}"