blueprint:
  name: "[Blueprint] Notify On State Change"
  description: Sends a notification when the state of a specified sensor changes.
  domain: automation
  source_url: https://wectrl.io
  input:
    target_sensor:
      name: Sensor
      description: Select the sensor you want to monitor for state changes.
      selector:
        entity:
          domain: 
            - sensor
            - binary_sensor
    notify_service:
      name: Notification Service
      description: Select the notification service you want to use.
      default: notify.notify
      selector:
        text:
    notification_text:
      name: Notification Text
      description: Customize the message text for the notification.
      default: "The {{ trigger.to_state.name }} changed to {{ state_translated(trigger.to_state.entity_id) }}!"
      selector:
        text:
    notification_title:
      name: Notification Title
      description: Customize the title text for the notification.
      default: "State change"
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input 'target_sensor'

condition:
  - condition: template
    value_template: "{{ trigger.from_state != trigger.to_state }}"

action:
  - service: !input 'notify_service'
    data:
      title: !input 'notification_title'
      message: !input 'notification_text'

mode: single
